# Generated by Django 5.1 on 2024-10-26 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaivariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GARLIC'), ('KI', 'KIWI'), ('PL', 'PLAIN'), ('SP', 'SPICY'), ('EL', 'ELACHI')], default='PL', max_length=2)),
            ],
        ),
    ]
